/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as ThreadsThreadIdImport } from './routes/threads/$threadId'
import { Route as AuthenticationSignUpImport } from './routes/authentication/sign-up'
import { Route as AuthenticationSignInImport } from './routes/authentication/sign-in'
import { Route as AuthenticationForgotPasswordImport } from './routes/authentication/forgot-password'
import { Route as ThreadsThreadIdPostsImport } from './routes/threads/$threadId_.posts'
import { Route as ThreadsThreadIdPostsNewImport } from './routes/threads/$threadId_.posts_.new'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThreadsThreadIdRoute = ThreadsThreadIdImport.update({
  id: '/threads/$threadId',
  path: '/threads/$threadId',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationSignUpRoute = AuthenticationSignUpImport.update({
  id: '/authentication/sign-up',
  path: '/authentication/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationSignInRoute = AuthenticationSignInImport.update({
  id: '/authentication/sign-in',
  path: '/authentication/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationForgotPasswordRoute =
  AuthenticationForgotPasswordImport.update({
    id: '/authentication/forgot-password',
    path: '/authentication/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)

const ThreadsThreadIdPostsRoute = ThreadsThreadIdPostsImport.update({
  id: '/threads/$threadId_/posts',
  path: '/threads/$threadId/posts',
  getParentRoute: () => rootRoute,
} as any)

const ThreadsThreadIdPostsNewRoute = ThreadsThreadIdPostsNewImport.update({
  id: '/threads/$threadId_/posts_/new',
  path: '/threads/$threadId/posts/new',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/authentication/forgot-password': {
      id: '/authentication/forgot-password'
      path: '/authentication/forgot-password'
      fullPath: '/authentication/forgot-password'
      preLoaderRoute: typeof AuthenticationForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/authentication/sign-in': {
      id: '/authentication/sign-in'
      path: '/authentication/sign-in'
      fullPath: '/authentication/sign-in'
      preLoaderRoute: typeof AuthenticationSignInImport
      parentRoute: typeof rootRoute
    }
    '/authentication/sign-up': {
      id: '/authentication/sign-up'
      path: '/authentication/sign-up'
      fullPath: '/authentication/sign-up'
      preLoaderRoute: typeof AuthenticationSignUpImport
      parentRoute: typeof rootRoute
    }
    '/threads/$threadId': {
      id: '/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof ThreadsThreadIdImport
      parentRoute: typeof rootRoute
    }
    '/threads/$threadId_/posts': {
      id: '/threads/$threadId_/posts'
      path: '/threads/$threadId/posts'
      fullPath: '/threads/$threadId/posts'
      preLoaderRoute: typeof ThreadsThreadIdPostsImport
      parentRoute: typeof rootRoute
    }
    '/threads/$threadId_/posts_/new': {
      id: '/threads/$threadId_/posts_/new'
      path: '/threads/$threadId/posts/new'
      fullPath: '/threads/$threadId/posts/new'
      preLoaderRoute: typeof ThreadsThreadIdPostsNewImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/authentication/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/authentication/sign-in': typeof AuthenticationSignInRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/$threadId/posts': typeof ThreadsThreadIdPostsRoute
  '/threads/$threadId/posts/new': typeof ThreadsThreadIdPostsNewRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/authentication/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/authentication/sign-in': typeof AuthenticationSignInRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/$threadId/posts': typeof ThreadsThreadIdPostsRoute
  '/threads/$threadId/posts/new': typeof ThreadsThreadIdPostsNewRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/authentication/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/authentication/sign-in': typeof AuthenticationSignInRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
  '/threads/$threadId': typeof ThreadsThreadIdRoute
  '/threads/$threadId_/posts': typeof ThreadsThreadIdPostsRoute
  '/threads/$threadId_/posts_/new': typeof ThreadsThreadIdPostsNewRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/authentication/forgot-password'
    | '/authentication/sign-in'
    | '/authentication/sign-up'
    | '/threads/$threadId'
    | '/threads/$threadId/posts'
    | '/threads/$threadId/posts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/authentication/forgot-password'
    | '/authentication/sign-in'
    | '/authentication/sign-up'
    | '/threads/$threadId'
    | '/threads/$threadId/posts'
    | '/threads/$threadId/posts/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/authentication/forgot-password'
    | '/authentication/sign-in'
    | '/authentication/sign-up'
    | '/threads/$threadId'
    | '/threads/$threadId_/posts'
    | '/threads/$threadId_/posts_/new'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AuthenticationForgotPasswordRoute: typeof AuthenticationForgotPasswordRoute
  AuthenticationSignInRoute: typeof AuthenticationSignInRoute
  AuthenticationSignUpRoute: typeof AuthenticationSignUpRoute
  ThreadsThreadIdRoute: typeof ThreadsThreadIdRoute
  ThreadsThreadIdPostsRoute: typeof ThreadsThreadIdPostsRoute
  ThreadsThreadIdPostsNewRoute: typeof ThreadsThreadIdPostsNewRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AuthenticationForgotPasswordRoute: AuthenticationForgotPasswordRoute,
  AuthenticationSignInRoute: AuthenticationSignInRoute,
  AuthenticationSignUpRoute: AuthenticationSignUpRoute,
  ThreadsThreadIdRoute: ThreadsThreadIdRoute,
  ThreadsThreadIdPostsRoute: ThreadsThreadIdPostsRoute,
  ThreadsThreadIdPostsNewRoute: ThreadsThreadIdPostsNewRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/authentication/forgot-password",
        "/authentication/sign-in",
        "/authentication/sign-up",
        "/threads/$threadId",
        "/threads/$threadId_/posts",
        "/threads/$threadId_/posts_/new"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/authentication/forgot-password": {
      "filePath": "authentication/forgot-password.tsx"
    },
    "/authentication/sign-in": {
      "filePath": "authentication/sign-in.tsx"
    },
    "/authentication/sign-up": {
      "filePath": "authentication/sign-up.tsx"
    },
    "/threads/$threadId": {
      "filePath": "threads/$threadId.tsx"
    },
    "/threads/$threadId_/posts": {
      "filePath": "threads/$threadId_.posts.tsx"
    },
    "/threads/$threadId_/posts_/new": {
      "filePath": "threads/$threadId_.posts_.new.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
