/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticationSignUpImport } from './routes/authentication/sign-up'
import { Route as AuthenticationSignInImport } from './routes/authentication/sign-in'
import { Route as AuthenticationForgotPasswordImport } from './routes/authentication/forgot-password'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationSignUpRoute = AuthenticationSignUpImport.update({
  id: '/authentication/sign-up',
  path: '/authentication/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationSignInRoute = AuthenticationSignInImport.update({
  id: '/authentication/sign-in',
  path: '/authentication/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationForgotPasswordRoute =
  AuthenticationForgotPasswordImport.update({
    id: '/authentication/forgot-password',
    path: '/authentication/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/authentication/forgot-password': {
      id: '/authentication/forgot-password'
      path: '/authentication/forgot-password'
      fullPath: '/authentication/forgot-password'
      preLoaderRoute: typeof AuthenticationForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/authentication/sign-in': {
      id: '/authentication/sign-in'
      path: '/authentication/sign-in'
      fullPath: '/authentication/sign-in'
      preLoaderRoute: typeof AuthenticationSignInImport
      parentRoute: typeof rootRoute
    }
    '/authentication/sign-up': {
      id: '/authentication/sign-up'
      path: '/authentication/sign-up'
      fullPath: '/authentication/sign-up'
      preLoaderRoute: typeof AuthenticationSignUpImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authentication/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/authentication/sign-in': typeof AuthenticationSignInRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authentication/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/authentication/sign-in': typeof AuthenticationSignInRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/authentication/forgot-password': typeof AuthenticationForgotPasswordRoute
  '/authentication/sign-in': typeof AuthenticationSignInRoute
  '/authentication/sign-up': typeof AuthenticationSignUpRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authentication/forgot-password'
    | '/authentication/sign-in'
    | '/authentication/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authentication/forgot-password'
    | '/authentication/sign-in'
    | '/authentication/sign-up'
  id:
    | '__root__'
    | '/'
    | '/authentication/forgot-password'
    | '/authentication/sign-in'
    | '/authentication/sign-up'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticationForgotPasswordRoute: typeof AuthenticationForgotPasswordRoute
  AuthenticationSignInRoute: typeof AuthenticationSignInRoute
  AuthenticationSignUpRoute: typeof AuthenticationSignUpRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticationForgotPasswordRoute: AuthenticationForgotPasswordRoute,
  AuthenticationSignInRoute: AuthenticationSignInRoute,
  AuthenticationSignUpRoute: AuthenticationSignUpRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/authentication/forgot-password",
        "/authentication/sign-in",
        "/authentication/sign-up"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/authentication/forgot-password": {
      "filePath": "authentication/forgot-password.tsx"
    },
    "/authentication/sign-in": {
      "filePath": "authentication/sign-in.tsx"
    },
    "/authentication/sign-up": {
      "filePath": "authentication/sign-up.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
